### PR TITLE
Make sure to really fail silently

### PR DESCRIPTION
**Pull request by morpheus65535**
Exemple: urlsplit() raising ValueError("Invalid IPv6 URL")

### CODE REVIEW

**Comment by barseghyanartur** [comment]
@morpheus65535:

Thanks for reporting this!

I see it indeed failing on things like:

```pyhton
get_tld('https://user:password[@host.com', fail_silently=True)
```

or:

```pyhton
get_tld('https://user[@host.com', fail_silently=True)
```

Could you come up with a test case for this?

**Comment by morpheus65535** [comment]
TBH I have zero experience with pytest (or test in general). Also, I can see that it raise an exception here and I'm not sure how you want to deal with this: do we still add other `if fail_silently` indefinitely? I would like your input here.

**Comment by morpheus65535** [comment]
Seems like settings this to None isn't a good idea: https://github.com/barseghyanartur/tld/pull/119/files#diff-11903c526295c8fa35c765c520ee37e92277984c69d24492c53f5802a7cdb2fdR328

It need to be dealed with later on and I'm not sure in control of you code base enough to deal with it properly AND efficiently.

**Comment by barseghyanartur** [comment]
Good questions. I'll take a closer look at it.

Apart from that, I assumed you do have a lot of testing experience (looking at number of your contributions in the bazarr repository).

**Comment by morpheus65535** [comment]
> Apart from that, I assumed you do have a lot of testing experience (looking at number of your contributions in the bazarr repository).

Manually testing, yes. Writing and running automated test cas, unfortunately not.

**Comment by morpheus65535** [comment]
I hope I did it properly. Let me know if you need something else! :-)

**Comment by morpheus65535** [comment]
Seems like I didn't... any help here?

**Comment by barseghyanartur** [comment]
@morpheus65535:

Sorry, working on updating the CI. Will release one day soon.

**Comment by morpheus65535** [comment]
@barseghyanartur no problem, thanks!

**Comment by barseghyanartur** [comment]
Released in 0.12.7.

**Pull request merged**
