### PR TITLE
Fix #49 - correctly handling nested tlds

### LINKED ISSUE #49: https://fedoraproject.org/  raise TldDomainNotFound
tld.exceptions.TldDomainNotFound: Domain www.fedoraproject.org didn't match any existing TLD name!

https://platform.sh/blog/speed-confidence-and-simplicity-what-our-34m-raise-means-for-you

tld.exceptions.TldDomainNotFound: Domain platform.sh didn't match any existing TLD name!

### PR DESCRIPTION
**Pull request by Yomguithereal**
@barseghyanartur here's the fix. The code wasn't correctly handling nested tld cases sometimes.

### CODE REVIEW

**Comment by barseghyanartur** [comment]
@Yomguithereal:

Awesome! Thanks!

**Comment by sebix** [comment]
Are you sure this is correct? That `cloud.fedoraproject.org` is a [TLD](https://en.wikipedia.org/wiki/Top-level_domain)?

**Comment by barseghyanartur** [comment]
@sebix:

At the moment it's as follows:

```
In [1]: from tld import get_tld

In [2]: get_tld('cloud.fedoraproject.org', fix_protocol=True)
Out[2]: 'fedoraproject.org'
```

**Comment by Yomguithereal** [comment]
@sebix yes it is. Search for it in the [list](https://publicsuffix.org/list/public_suffix_list.dat). However it is a private suffix. If you want to avoid searching private suffix and you'd rather return `org`, you can set the `search_private` kwarg to `False`.

**Comment by barseghyanartur** [comment]
However, I think this should not cause an exception.

```
get_tld('cloud.fedoraproject.org', fix_protocol=True, search_private=False)
```

At the moment it does - `TldDomainNotFound: Domain cloud.fedoraproject.org didn't match any existing TLD name!`.

**Comment by sebix** [comment]
> Search for it in the list. However it is a private suffix.

Nevertheless `[cloud.]fedoraproject.org` is not a *top* level domain. `.org` is. The public/private suffix list not a list of top level domains but everybody believes it is.

https://publicsuffix.org/list/
> A public suffix is a set of DNS names or wildcards concatenated with dots. It represents the part of a domain name which is not under the control of the individual registrant.

https://en.wikipedia.org/wiki/Top-level_domain
> A top-level domain (TLD) is one of the domains at the highest level in the hierarchical Domain Name System of the Internet.

public/private suffix != TLD

**Comment by Yomguithereal** [comment]
@sebix I see what you mean. Would [this](https://www.iana.org/domains/root/db) be the actual TLD then?

**Comment by sebix** [comment]
Looks good. Here it is machine readable:
https://data.iana.org/TLD/tlds-alpha-by-domain.txt

If you ignore all the private suffixes from the public suffix list, you
get the (perfectly fine) domain suffix, for example `gv.at`. But a
domain suffix is not a TLD. You can always get the last part as tld (by
definition). Validating against a list can be done too, yes.

That has been already been discussed several times in the past here,
e.g.: https://github.com/barseghyanartur/tld/issues/32
https://github.com/barseghyanartur/tld/issues/27

**Comment by Yomguithereal** [comment]
So for your use cases, since retrieving the actual tld is trivial (just last part of the domain name), I guess what's your interested in is to know whether the tld actually exist or not? Is that it?

@barseghyanartur I guess we will need again to fix the library's naming?

**Comment by barseghyanartur** [comment]
@Yomguithereal:

Well, the `Extracts the top level domain (TLD) from the URL given.` sounds correct still.

The list mentioned by @sebix looks really simple (I like it).

While it's still possible to achieve the behaviour expected by @sebix (and not expected by some other people) using Mozilla's list by simply providing `search_private=False`. 

At the moment, `search_private` is set to True by default. We can change the default value to False in the upcoming releases.

What I think is that I can abstragate most of the logic into a separate `BaseIndex` class and allow usage of multiple indexes (Mozilla's list would still remain default; at least for a couple of releases).

Does it sound like a plan to you?

**Comment by sebix** [comment]
I don't use your library and do not plan to do so. I found that your
algorithm is wrong and just inform you about it - like I already did a
few months ago. That's all I (can) do.

Here is someone using the library to get the actual TLD:
https://github.com/stratosphereips/whois-similarity-distance/blob/ea2ccde596680bdffb2d485d71c5c23ab6a6ab64/whois_similarity_distance/util/whois_obj.py#L323
https://github.com/stratosphereips/whois-similarity-distance/blob/ea2ccde596680bdffb2d485d71c5c23ab6a6ab64/whois_similarity_distance/util/whois_obj.py#L186

**Pull request merged**
