### PR TITLE
setup.py: use entry_points.console_scripts

### PR DESCRIPTION
**Pull request by flokli**
Part of https://github.com/barseghyanartur/tld/issues/54.

This uses `entry_points.console_scripts` in setup.py to use `tld.utils:update_tld_names` directly, removing two layers of wrapper code.

### CODE REVIEW

**Comment by flokli** [comment]
This results in `bin/update-tld-names` being installed when instructing `python setup.py installed`, and `update-tld-names` appearing in `$PATH` when running `python setup.py develop`. Make sure this doesn't clash with other `update-tld-names` that might be in your path, too.

**Comment by flokli** [comment]
Turns out, getting tox to add the `console_tools` wrapper to `$PATH` seems to be rather complicated.

I dropped the test executing the wrapper, as we already call the destination function in a test - let's assume setuptools does its job.

**Comment by flokli** [comment]
ping @barseghyanartur ;-)

**Comment by barseghyanartur** [comment]
@flokli:

Hey, sorry for the delay. I'm afraid I won't merge your pull request fully, however I'll cherry pick some of the changes.

**Comment by barseghyanartur** [comment]
@flokli:

Hey, your changes have been merged into master. Thanks!

**Pull request merged**
